version: '3.4'

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Enes123!"
    user: root
    ports:
      - 1433:1433
    volumes:
      - mssql-volume:/var/opt/mssql
      
volumes:
  mssql-volume: